from ActivityStateTests import *
from StatementTests import *
from ActivityProfileTests import *
from AgentProfileTests import *
from AgentsTests import *
from ActivityManagerTests import *
from AgentManagerTests import *
from ActivityTests import *
from StatementManagerTests import *
from StatementMoreTests import *
from OAuthTests import *
from OAuth2Tests import *
from AuthTests import *
from StatementFilterTests import *
from OAuthTests import *
from AttachmentAndSignedTests import *
