---

- name: Add Postgres apt repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  tags:
    - apt
    - postgres

- name: Add Postgres apt repo
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main" state=present
  tags:
    - apt
    - postgres
