name: Pylint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install umsgpack
        pip install cryptography
        pip install pylint-fail-under
  #lists pyling suggestions to improve the score & pylint score of the file
    - name: code review 
      run: find . -name '*.py' -print -exec pylint {} \;
      
  #fails the build if one file has pylint score below 7.0
    - name: Analysing the code with pylint
      run: |
            for file in */*.py; do pylint "$file" --fail-under=7.0; done
  #  - name: Analysing the code with pylint
  #    run: |
  #     pylint $(git ls-files '*.py')
